version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10 
    commands:
      - echo install step...
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Compiling application...
      - npm run build
  post_build:
    commands:
      - echo clean S3 diag app...
      - aws s3 rm s3://wild.itsmycity.fr --recursive
      - echo Copy diag app to S3...
      - aws s3 cp --recursive --acl public-read ./build s3://wild.itsmycity.fr/
      - echo set the cache-control headers for index.html to prevent browser caching
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://wild.itsmycity.fr
      - echo invalidate cloudfront
      - aws cloudfront create-invalidation --distribution-id E3JJIC4NXCLEAZ --paths '/*'
artifacts:
  name: FrontBuildArtifact
  base-directory: ./build
  files:
    - '**/*'
